channels:
- anaconda
- conda-forge
dependencies:
- python=3.9.21
- pip:
  - azureml-automl-dnn-nlp~=1.59.0
  - inference-schema
  - azureml-defaults~=1.59.0
  - mlflow-skinny
- numpy==1.21.6
- pandas==1.3.5
- psutil>=5.2.2,<6.0.0
- pytorch==1.13.1
name: project_environment
